# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/zhang/dbs-project-36

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/zhang/dbs-project-36

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/zhang/dbs-project-36/CMakeFiles /mnt/c/Users/zhang/dbs-project-36//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/zhang/dbs-project-36/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named database

# Build rule for target.
database: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 database
.PHONY : database

# fast build rule for target.
database/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/database.dir/build.make CMakeFiles/database.dir/build
.PHONY : database/fast

#=============================================================================
# Target rules for targets named antlr4_runtime

# Build rule for target.
antlr4_runtime: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 antlr4_runtime
.PHONY : antlr4_runtime

# fast build rule for target.
antlr4_runtime/fast:
	$(MAKE) $(MAKESILENT) -f 3rd_party/antlr4_runtime/CMakeFiles/antlr4_runtime.dir/build.make 3rd_party/antlr4_runtime/CMakeFiles/antlr4_runtime.dir/build
.PHONY : antlr4_runtime/fast

src/filesystem/testfilesystem.o: src/filesystem/testfilesystem.cpp.o
.PHONY : src/filesystem/testfilesystem.o

# target to build an object file
src/filesystem/testfilesystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/database.dir/build.make CMakeFiles/database.dir/src/filesystem/testfilesystem.cpp.o
.PHONY : src/filesystem/testfilesystem.cpp.o

src/filesystem/testfilesystem.i: src/filesystem/testfilesystem.cpp.i
.PHONY : src/filesystem/testfilesystem.i

# target to preprocess a source file
src/filesystem/testfilesystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/database.dir/build.make CMakeFiles/database.dir/src/filesystem/testfilesystem.cpp.i
.PHONY : src/filesystem/testfilesystem.cpp.i

src/filesystem/testfilesystem.s: src/filesystem/testfilesystem.cpp.s
.PHONY : src/filesystem/testfilesystem.s

# target to generate assembly for a file
src/filesystem/testfilesystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/database.dir/build.make CMakeFiles/database.dir/src/filesystem/testfilesystem.cpp.s
.PHONY : src/filesystem/testfilesystem.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/database.dir/build.make CMakeFiles/database.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/database.dir/build.make CMakeFiles/database.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/database.dir/build.make CMakeFiles/database.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/parser/parser/SQLBaseVisitor.o: src/parser/parser/SQLBaseVisitor.cpp.o
.PHONY : src/parser/parser/SQLBaseVisitor.o

# target to build an object file
src/parser/parser/SQLBaseVisitor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/database.dir/build.make CMakeFiles/database.dir/src/parser/parser/SQLBaseVisitor.cpp.o
.PHONY : src/parser/parser/SQLBaseVisitor.cpp.o

src/parser/parser/SQLBaseVisitor.i: src/parser/parser/SQLBaseVisitor.cpp.i
.PHONY : src/parser/parser/SQLBaseVisitor.i

# target to preprocess a source file
src/parser/parser/SQLBaseVisitor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/database.dir/build.make CMakeFiles/database.dir/src/parser/parser/SQLBaseVisitor.cpp.i
.PHONY : src/parser/parser/SQLBaseVisitor.cpp.i

src/parser/parser/SQLBaseVisitor.s: src/parser/parser/SQLBaseVisitor.cpp.s
.PHONY : src/parser/parser/SQLBaseVisitor.s

# target to generate assembly for a file
src/parser/parser/SQLBaseVisitor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/database.dir/build.make CMakeFiles/database.dir/src/parser/parser/SQLBaseVisitor.cpp.s
.PHONY : src/parser/parser/SQLBaseVisitor.cpp.s

src/parser/parser/SQLLexer.o: src/parser/parser/SQLLexer.cpp.o
.PHONY : src/parser/parser/SQLLexer.o

# target to build an object file
src/parser/parser/SQLLexer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/database.dir/build.make CMakeFiles/database.dir/src/parser/parser/SQLLexer.cpp.o
.PHONY : src/parser/parser/SQLLexer.cpp.o

src/parser/parser/SQLLexer.i: src/parser/parser/SQLLexer.cpp.i
.PHONY : src/parser/parser/SQLLexer.i

# target to preprocess a source file
src/parser/parser/SQLLexer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/database.dir/build.make CMakeFiles/database.dir/src/parser/parser/SQLLexer.cpp.i
.PHONY : src/parser/parser/SQLLexer.cpp.i

src/parser/parser/SQLLexer.s: src/parser/parser/SQLLexer.cpp.s
.PHONY : src/parser/parser/SQLLexer.s

# target to generate assembly for a file
src/parser/parser/SQLLexer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/database.dir/build.make CMakeFiles/database.dir/src/parser/parser/SQLLexer.cpp.s
.PHONY : src/parser/parser/SQLLexer.cpp.s

src/parser/parser/SQLParser.o: src/parser/parser/SQLParser.cpp.o
.PHONY : src/parser/parser/SQLParser.o

# target to build an object file
src/parser/parser/SQLParser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/database.dir/build.make CMakeFiles/database.dir/src/parser/parser/SQLParser.cpp.o
.PHONY : src/parser/parser/SQLParser.cpp.o

src/parser/parser/SQLParser.i: src/parser/parser/SQLParser.cpp.i
.PHONY : src/parser/parser/SQLParser.i

# target to preprocess a source file
src/parser/parser/SQLParser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/database.dir/build.make CMakeFiles/database.dir/src/parser/parser/SQLParser.cpp.i
.PHONY : src/parser/parser/SQLParser.cpp.i

src/parser/parser/SQLParser.s: src/parser/parser/SQLParser.cpp.s
.PHONY : src/parser/parser/SQLParser.s

# target to generate assembly for a file
src/parser/parser/SQLParser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/database.dir/build.make CMakeFiles/database.dir/src/parser/parser/SQLParser.cpp.s
.PHONY : src/parser/parser/SQLParser.cpp.s

src/parser/parser/SQLVisitor.o: src/parser/parser/SQLVisitor.cpp.o
.PHONY : src/parser/parser/SQLVisitor.o

# target to build an object file
src/parser/parser/SQLVisitor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/database.dir/build.make CMakeFiles/database.dir/src/parser/parser/SQLVisitor.cpp.o
.PHONY : src/parser/parser/SQLVisitor.cpp.o

src/parser/parser/SQLVisitor.i: src/parser/parser/SQLVisitor.cpp.i
.PHONY : src/parser/parser/SQLVisitor.i

# target to preprocess a source file
src/parser/parser/SQLVisitor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/database.dir/build.make CMakeFiles/database.dir/src/parser/parser/SQLVisitor.cpp.i
.PHONY : src/parser/parser/SQLVisitor.cpp.i

src/parser/parser/SQLVisitor.s: src/parser/parser/SQLVisitor.cpp.s
.PHONY : src/parser/parser/SQLVisitor.s

# target to generate assembly for a file
src/parser/parser/SQLVisitor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/database.dir/build.make CMakeFiles/database.dir/src/parser/parser/SQLVisitor.cpp.s
.PHONY : src/parser/parser/SQLVisitor.cpp.s

src/system/dbsystem.o: src/system/dbsystem.cpp.o
.PHONY : src/system/dbsystem.o

# target to build an object file
src/system/dbsystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/database.dir/build.make CMakeFiles/database.dir/src/system/dbsystem.cpp.o
.PHONY : src/system/dbsystem.cpp.o

src/system/dbsystem.i: src/system/dbsystem.cpp.i
.PHONY : src/system/dbsystem.i

# target to preprocess a source file
src/system/dbsystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/database.dir/build.make CMakeFiles/database.dir/src/system/dbsystem.cpp.i
.PHONY : src/system/dbsystem.cpp.i

src/system/dbsystem.s: src/system/dbsystem.cpp.s
.PHONY : src/system/dbsystem.s

# target to generate assembly for a file
src/system/dbsystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/database.dir/build.make CMakeFiles/database.dir/src/system/dbsystem.cpp.s
.PHONY : src/system/dbsystem.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... antlr4_runtime"
	@echo "... database"
	@echo "... src/filesystem/testfilesystem.o"
	@echo "... src/filesystem/testfilesystem.i"
	@echo "... src/filesystem/testfilesystem.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/parser/parser/SQLBaseVisitor.o"
	@echo "... src/parser/parser/SQLBaseVisitor.i"
	@echo "... src/parser/parser/SQLBaseVisitor.s"
	@echo "... src/parser/parser/SQLLexer.o"
	@echo "... src/parser/parser/SQLLexer.i"
	@echo "... src/parser/parser/SQLLexer.s"
	@echo "... src/parser/parser/SQLParser.o"
	@echo "... src/parser/parser/SQLParser.i"
	@echo "... src/parser/parser/SQLParser.s"
	@echo "... src/parser/parser/SQLVisitor.o"
	@echo "... src/parser/parser/SQLVisitor.i"
	@echo "... src/parser/parser/SQLVisitor.s"
	@echo "... src/system/dbsystem.o"
	@echo "... src/system/dbsystem.i"
	@echo "... src/system/dbsystem.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

